// Archived bots — excluded from new tournaments and the HUD strategy
// dropdown, but still loadable by name for replays and league watching.
//
// This file is auto-managed by:
//   node tournament/run.js --archive-bottom N      # archive bottom N tiers
//   node tournament/run.js --archive-clear         # remove all
//   node tournament/run.js --archive-add A,B,C
//   node tournament/run.js --archive-remove A,B,C
//
// You can also hand-edit it.
export const ARCHIVED = [
  "Avalanche",
  "Berserker",
  "Bully_05",
  "Cautious",
  "Cluster_01",
  "Cluster_02",
  "Cluster_03",
  "Cluster_04",
  "Cluster_05",
  "Cluster_06",
  "Cluster_07",
  "Cluster_08",
  "Cluster_09",
  "Cluster_10",
  "Defender",
  "Drift_E",
  "Drift_EvN",
  "Drift_N",
  "Drift_NE",
  "Drift_NW",
  "Drift_S",
  "Drift_SE",
  "Drift_SW",
  "Drift_W",
  "Drift_WvS",
  "Hunter",
  "Pacifist_05",
  "Pacifist_06",
  "Pacifist_07",
  "Pacifist_08",
  "Pacifist_09",
  "Pacifist_10",
  "Patient_01",
  "Patient_02",
  "Patient_03",
  "Patient_04",
  "Patient_05",
  "Patient_06",
  "Patient_07",
  "Patient_08",
  "Patient_09",
  "Patient_10",
  "Phalanx",
  "Probe_01",
  "Probe_02",
  "Probe_03",
  "Probe_04",
  "Probe_05",
  "Probe_06",
  "Probe_07",
  "Probe_08",
  "Probe_09",
  "Probe_10",
  "Pulse_01",
  "Pulse_02",
  "Pulse_03",
  "Pulse_04",
  "Pulse_05",
  "Pulse_06",
  "Pulse_07",
  "Pulse_08",
  "Pulse_09",
  "Pulse_10",
  "Scatter_02",
  "Scatter_03",
  "Scatter_04",
  "Scatter_05",
  "Scatter_06",
  "Scatter_07",
  "Scatter_09",
  "Scout",
  "Stencil_01",
  "Stencil_03",
  "Stencil_05",
  "Stencil_06",
  "Stencil_07",
  "Stencil_08",
  "Stencil_09",
  "Stencil_10",
  "Swarm",
  "Tactician",
  "Turtle",
  "Vampire",
];
