// Archived bots — excluded from new tournaments and the HUD strategy
// dropdown, but still loadable by name for replays and league watching.
//
// This file is auto-managed by:
//   node tournament/run.js --archive-bottom N      # archive bottom N tiers
//   node tournament/run.js --archive-clear         # remove all
//   node tournament/run.js --archive-add A,B,C
//   node tournament/run.js --archive-remove A,B,C
//   node tournament/run.js --register-descendant   # auto-archives the
//                                                  # globally weakest bot
//
// You can also hand-edit it.
export const ARCHIVED = [
  "Anvil",
  "Avalanche",
  "Berserker",
  "Bully_07",
  "Cluster_01",
  "Cluster_03",
  "Cluster_04",
  "Cluster_10",
  "Defender",
  "Drift_E",
  "Drift_NW",
  "Drift_SE",
  "Drift_SW",
  "Drift_W",
  "Hunter",
  "Hunter_02",
  "Hunter_05",
  "Hunter_06",
  "Opportunist",
  "Pacifist_07",
  "Patient_01",
  "Patient_03",
  "Patient_04",
  "Patient_05",
  "Patient_06",
  "Patient_07",
  "Patient_09",
  "Probe_01",
  "Probe_02",
  "Probe_03",
  "Probe_04",
  "Probe_05",
  "Probe_06",
  "Probe_07",
  "Probe_08",
  "Probe_09",
  "Probe_10",
  "Pulse_01",
  "Pulse_02",
  "Pulse_03",
  "Pulse_05",
  "Pulse_06",
  "Pulse_07",
  "Pulse_08",
  "Pulse_09",
  "Pulse_10",
  "Scatter_03",
  "Scatter_05",
  "Scatter_06",
  "Scatter_08",
  "Scout",
  "Spearhead_g1_7f5793",
  "Stencil_01",
  "Stencil_02",
  "Stencil_03",
  "Stencil_04",
  "Stencil_05",
  "Stencil_06",
  "Stencil_07",
  "Stencil_08",
  "Stencil_09",
  "Stencil_10",
  "Surge",
  "Swarm",
  "Tactician",
  "Vampire",
];
